name: Python application

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu for the runner

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2  # This checks out your repository onto the runner

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Use the appropriate Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt

    - name: Run tests with pytest
      run: |
        pytest  # Run the tests using pytest
